### ISSUE TITLE
Unable to cast char to int

### ISSUE THREAD

**Issue by nulldatamap** [fleabitdev/glsp#22]
Trying to invoke something like:
```
(int \a)
```
Causes the error message:
```
error: cannot cast argument to an int
```
Even though looking at [the code](https://github.com/fleabitdev/glsp/blob/master/glsp-stdlib/src/misc.rs#L187) and documentation one would think it should work.

**Comment by fleabitdev** [comment]
Good catch, thanks! Fixed by 54083de591a91bee3d973c963288126cb5de2a34.
