### ISSUE TITLE
Crash on emoji in string

### ISSUE THREAD

**Issue by tyomitch** [fleabitdev/glsp#26]
`(prn "👦")` fails with `thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside '��' (bytes 0..4) of `��`'`

**Comment by fleabitdev** [comment]
Good catch, thanks!

The bug is at line 617 of parse.rs. Should be an easy fix. I'll patch it before the 0.2 release.

**Comment by fleabitdev** [comment]
Fixed by 6a3a218 :)
