### ISSUE TITLE
What's the prefered method for using types from other libraries as rdata?

### ISSUE THREAD

**Issue by Grinshpon** [fleabitdev/glsp#29]
The 0.1 version of the documentation had an `rdata!` macro and this example:

```Rust
rdata! {
    struct Sprite {
        name: Sym,
        texture: ggez::graphics::Image
    }
}
```

But in 0.2 the macro is gone and it seems the only way to do this is to wrap the type and create a custom impl. Is there a different, preferred way of doing this, or will the `rdata!` macro come back at some point?

**Comment by fleabitdev** [comment]
The rules surrounding Rust data have been [greatly simplified](https://www.reddit.com/r/rust/comments/kp77vw/version_02_of_gamelisp_a_scripting_language_for/ghvc0wn/) in 0.2. You can now pass values of any `'static` type to the `glsp::rdata` function, with no fuss:

```rust
let file_rdata: Root<RData> = glsp::rdata(File::open("example.png")?);
```

The new [Rust Bindings](https://gamelisp.rs/reference/rust-bindings.html) section of the reference manual has all of the details.

**Comment by Grinshpon** [comment]
> 
> 
> The rules surrounding Rust data have been [greatly simplified](https://www.reddit.com/r/rust/comments/kp77vw/version_02_of_gamelisp_a_scripting_language_for/ghvc0wn/) in 0.2. You can now pass values of any `'static` type to the `glsp::rdata` function, with no fuss:
> 
> ```rust
> let file_rdata: Root<RData> = glsp::rdata(File::open("example.png")?);
> ```
> 
> The new [Rust Bindings](https://gamelisp.rs/reference/rust-bindings.html) section of the reference manual has all of the details.

~~Hmm, I guess I thought otherwise because I keep getting an error pertaining to some ggez types, specifically [DrawMode](https://docs.rs/ggez/0.5.1/ggez/graphics/enum.DrawMode.html) and [Color](https://docs.rs/ggez/0.5.1/ggez/graphics/struct.Color.html). The error complains about `WrappedCall` not being implemented. Should I open a new issue for this?~~

Edit: I see what my issue was now, I was conflating `IntoVal` and `FromVal`, and skimmed over the part in the documentation talking about rfn arguments. All I needed to do was take a reference to the type. I'm sorry, I should have paid more attention to the documentation!
