### ISSUE TITLE
[General] How do I get this if I want to make modifications to the code?

### ISSUE THREAD

**Issue by Zireael07** [fleabitdev/glsp#33]
The standard way is to specify it in Cargo.toml: 
`glsp = "0.2"`

but what if I want to modify the code after getting it?

**Comment by fleabitdev** [comment]
Thanks for your interest!

You would need to fork the `fleabitdev/glsp` repository. GitHub provides some instructions [here](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo).

**Comment by Zireael07** [comment]
Fork the repo, and drop it in my existing project you mean?

A bit of a pity that cargo.toml doesn't put the code somewhere accessible after getting it...
