### ISSUE TITLE
Allow meths in lib! macro

### ISSUE THREAD

**Issue by thorlucas** [fleabitdev/glsp#7]
We can add a `meths` in an `rdata!` macro like so:

``` rust
rdata! {
	#[derive(Clone)]
	struct AudioClip {
		samples: Vec<i16>,
		channels: Channels
	}

	meths {
		get "duration": AudioClip::duration,
		"play": AudioClip::play
	}
}
```

``` lisp
(.play my-clip)
```

For `lib!`, a similar thing should be allowed, except now the names are global functions:

``` rust
lib! {
    struct Devices {
        ...
    }
    
    meths {
        "add-device": Devices::add_device,
    }
}
```

``` lisp
(add-device (x y z))
```

**Comment by fleabitdev** [comment]
A very promising suggestion, thanks!

I'd prefer not to use the name `meths` to refer to something which isn't a method, so it would probably be called `rfns` instead.

I normally dislike providing two different ways to achieve the same thing, but this syntax would be so much nicer than having dozens of calls like:

    glsp::bind_rfn("add-device", rfn!(Devices::add_device))?;

The only time it would be possible to automatically register the rfns would be while calling `glsp::add_lib`. This would pose a problem if a library wants to access one of its own `RFn` bindings in its constructor - but that seems unlikely.

**Comment by fleabitdev** [comment]
Recent changes have eliminated the `lib!` macro altogether. In general, I'm also moving away from using macros to define Rust-to-GameLisp bindings; `glsp::bind_rfn` is likely to be left alone for the foreseeable future.
